In [101]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression

In [102]:
superBowl = pd.read_csv('simp_dataset.csv')
superBowl.set_index('SB', inplace=True)

In [103]:
superBowl.columns

Index(['Date', 'Attendance', 'QB  Winner', 'Coach Winner', 'Winner',
       'Winning Pts', 'QB Loser', 'Coach Loser', 'Loser', 'Losing Pts', 'MVP',
       'Stadium', 'City', 'State', 'Point Difference', 'temperature',
       'in/ out', 'Average Viewers', 'Total Viewers', 'TV_rating', 'TV_share',
       '30-sec Ads cost', 'competitive_score', 'winner_season_winning_pct',
       'winner_season_point_score', 'winner_season_point_allow',
       'winner_end_streak', 'winner_winning_streak', 'winner_losing_streak',
       'loser_season_winning_pct', 'loser_season_point_score',
       'loser_season_point_allow', 'loser_end_streak', 'loser_winning_streak',
       'loser_losing_streak'],
      dtype='object')

In [104]:
simp = superBowl.loc[:,"winner_season_winning_pct":"loser_losing_streak"]
simp.head()

,winner_season_winning_pct,winner_season_point_score,winner_season_point_allow,winner_end_streak,winner_winning_streak,winner_losing_streak,loser_season_winning_pct,loser_season_point_score,loser_season_point_allow,loser_end_streak,loser_winning_streak,loser_losing_streak
SB,,,,,,,,,,,,
I,0.857,335,163,W5,5,0,0.846,448,276,W3,3,0
II,0.692,332,209,L2,0,2,0.929,468,233,W10,10,0
III,0.786,419,280,W4,4,0,0.929,402,144,W8,8,0
IV,0.786,359,177,L1,0,1,0.857,379,133,L1,0,1
V,0.846,321,234,W4,4,0,0.714,299,221,W5,5,0

In [105]:
simp.drop(columns = ['winner_end_streak','loser_end_streak'], inplace=True)

In [106]:
winner = simp[[i for i in simp.columns if 'winner' in i]]
loser = simp[[i for i in simp.columns if 'loser' in i]]

In [107]:
winner.rename(columns=lambda x: x[7:], inplace=True)
loser.rename(columns=lambda x: x[6:], inplace=True)

In [108]:
winner['result'] = 1
loser['result']=0

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [109]:
winner

,season_winning_pct,season_point_score,season_point_allow,winning_streak,losing_streak,result
SB,,,,,,
I,0.857,335,163,5,0,1
II,0.692,332,209,0,2,1
III,0.786,419,280,4,0,1
IV,0.786,359,177,0,1,1
V,0.846,321,234,4,0,1
VI,0.786,406,222,7,0,1
VII,1.000,385,171,14,0,1
VIII,0.857,343,150,1,0,1
IX,0.750,305,189,2,0,1
X,0.857,373,162,0,1,1
XI,0.929,350,237,10,0,1
XII,0.857,345,212,4,0,1
XIII,0.875,356,195,5,0,1
XIV,0.750,416,262,1,0,1
XV,0.688,364,306,2,0,1
XVI,0.857,357,250,5,0,1
XVII,0.889,190,128,4,0,1
XVIII,0.750,442,338,1,0,1
XIX,0.938,475,227,9,0,1
XX,0.938,456,198,3,0,1
XXI,0.875,371,236,9,0,1
XXII,0.733,379,285,1,0,1
XXIII,0.625,369,294,0,1,1
XXIV,0.875,442,253,5,0,1
XXV,0.813,335,211,2,0,1
XXVI,0.875,485,224,0,1,1
XXVII,0.813,409,243,2,0,1
XXVIII,0.750,376,229,5,0,1
XXIX,0.813,505,296,0,1,1
XXX,0.750,435,291,2,0,1
XXXI,0.813,456,210,5,0,1
XXXII,0.750,472,287,1,0,1
XXXIII,0.875,501,309,1,0,1
XXXIV,0.813,526,242,0,1,1
XXXV,0.750,333,165,7,0,1
XXXVI,0.688,371,272,6,0,1
XXXVII,0.750,346,196,1,0,1
XXXVIII,0.875,348,238,12,0,1
XXXIX,0.875,437,260,2,0,1
XL,0.688,389,258,4,0,1
XLI,0.750,427,360,1,0,1
XLII,0.625,373,351,0,1,1
XLIII,0.750,347,223,1,0,1
XLIV,0.813,510,341,0,3,1
XLV,0.625,388,240,2,0,1
XLVI,0.563,394,400,2,0,1
XLVII,0.625,398,344,0,1,1
XLVIII,0.813,417,231,1,0,1
XLIX,0.750,468,313,0,1,1
L,0.750,355,296,2,0,1
LI,0.875,441,250,7,0,1
LII,0.813,457,295,0,1,1
LIII,0.688,436,325,2,0,1
LIV,0.750,451,308,6,0,1

In [110]:
loser

,season_winning_pct,season_point_score,season_point_allow,winning_streak,losing_streak,result
SB,,,,,,
I,0.846,448,276,3,0,0
II,0.929,468,233,10,0,0
III,0.929,402,144,8,0,0
IV,0.857,379,133,0,1,0
V,0.714,299,221,5,0,0
VI,0.769,315,174,1,0,0
VII,0.786,336,218,0,2,0
VIII,0.857,296,168,2,0,0
IX,0.714,310,195,3,0,0
X,0.786,356,276,3,0,0
XI,0.821,305,176,2,0,0
XII,0.857,274,148,0,1,0
XIII,0.750,384,208,6,0,0
XIV,0.563,323,309,0,1,0
XV,0.750,384,222,0,1,0
XVI,0.750,421,304,2,0,0
XVII,0.778,198,131,3,0,0
XVIII,0.875,541,332,9,0,0
XIX,0.875,513,298,2,0,0
XX,0.688,362,290,1,0,0
XXI,0.688,378,327,0,1,0
XXII,0.700,379,288,2,0,0
XXIII,0.700,379,288,2,0,0
XXIV,0.688,362,226,0,1,0
XXV,0.813,428,263,0,1,0
XXVI,0.813,458,318,0,1,0
XXVII,0.688,381,283,0,1,0
XXVIII,0.750,329,242,4,0,0
XXIX,0.688,381,306,2,0,0
XXX,0.688,407,327,0,1,0
XXXI,0.688,418,313,1,0,0
XXXII,0.813,422,282,5,0,0
XXXIII,0.875,442,289,9,0,0
XXXIV,0.813,392,324,4,0,0
XXXV,0.750,328,246,5,0,0
XXXVI,0.875,503,273,6,0,0
XXXVII,0.688,450,304,2,0,0
XXXVIII,0.688,325,304,3,0,0
XXXIX,0.813,386,260,0,2,0
XL,0.813,454,271,0,1,0
XLI,0.812,427,255,0,1,0
XLII,1.000,589,274,16,0,0
XLIII,0.563,427,426,1,0,0
XLIV,0.875,416,307,0,2,0
XLV,0.750,375,232,2,0,0
XLVI,0.813,513,342,8,0,0
XLVII,0.719,397,273,1,0,0
XLVIII,0.688,381,306,2,0,0
XLIX,0.750,394,254,6,0,0
L,0.938,500,308,1,0,0
LI,0.688,540,406,4,0,0
LII,0.813,458,296,3,0,0
LIII,0.813,527,384,2,0,0
LIV,0.813,479,310,2,0,0

In [111]:
winner.append(loser)

,season_winning_pct,season_point_score,season_point_allow,winning_streak,losing_streak,result
SB,,,,,,
I,0.857,335,163,5,0,1
II,0.692,332,209,0,2,1
III,0.786,419,280,4,0,1
IV,0.786,359,177,0,1,1
V,0.846,321,234,4,0,1
...,...,...,...,...,...,...
L,0.938,500,308,1,0,0
LI,0.688,540,406,4,0,0
LII,0.813,458,296,3,0,0
LIII,0.813,527,384,2,0,0
LIV,0.813,479,310,2,0,0